#!/bin/bash

cd /etc/swift

rm -f *.builder *.ring.gz backups/*.builder backups/*.ring.gz

STORAGE_NODE1='192.168.1.221'
STORAGE_NODE2='192.168.1.222'
STORAGE_NODE3='192.168.1.223'
STORAGE_NODE4=''
STORAGE_NODE5=''
STORAGE_NODE6=''
STORAGE_NODE7=''
STORAGE_NODE8=''
swift-ring-builder object.builder create 10 3 1
swift-ring-builder object.builder add r1z1-$STORAGE_NODE1:6000/sdb1 1
swift-ring-builder object.builder add r1z2-$STORAGE_NODE1:6000/sdc1 1
swift-ring-builder object.builder add r1z3-$STORAGE_NODE1:6000/sdd1 1
swift-ring-builder object.builder add r1z4-$STORAGE_NODE1:6000/sde1 1
swift-ring-builder object.builder add r2z1-$STORAGE_NODE2:6000/sdb1 1
swift-ring-builder object.builder add r2z2-$STORAGE_NODE2:6000/sdc1 1
swift-ring-builder object.builder add r2z3-$STORAGE_NODE2:6000/sdd1 1
swift-ring-builder object.builder add r2z4-$STORAGE_NODE2:6000/sde1 1
swift-ring-builder object.builder add r3z1-$STORAGE_NODE3:6000/sdb1 1
swift-ring-builder object.builder add r3z2-$STORAGE_NODE3:6000/sdc1 1
swift-ring-builder object.builder add r3z3-$STORAGE_NODE3:6000/sdd1 1
swift-ring-builder object.builder add r3z4-$STORAGE_NODE3:6000/sde1 1
swift-ring-builder object.builder rebalance
swift-ring-builder object-1.builder create 10 1 1
swift-ring-builder object-1.builder add r1z1-$STORAGE_NODE1:6000/sdb1 1
swift-ring-builder object-1.builder add r1z2-$STORAGE_NODE1:6000/sdc1 1
swift-ring-builder object-1.builder add r1z3-$STORAGE_NODE1:6000/sdd1 1
swift-ring-builder object-1.builder add r1z4-$STORAGE_NODE1:6000/sde1 1
swift-ring-builder object-1.builder add r2z1-$STORAGE_NODE2:6000/sdb1 1
swift-ring-builder object-1.builder add r2z2-$STORAGE_NODE2:6000/sdc1 1
swift-ring-builder object-1.builder add r2z3-$STORAGE_NODE2:6000/sdd1 1
swift-ring-builder object-1.builder add r2z4-$STORAGE_NODE2:6000/sde1 1
swift-ring-builder object-1.builder add r3z1-$STORAGE_NODE3:6000/sdb1 1
swift-ring-builder object-1.builder add r3z2-$STORAGE_NODE3:6000/sdc1 1
swift-ring-builder object-1.builder add r3z3-$STORAGE_NODE3:6000/sdd1 1
swift-ring-builder object-1.builder add r3z4-$STORAGE_NODE3:6000/sde1 1
swift-ring-builder object-1.builder rebalance
swift-ring-builder object-2.builder create 10 6 1
swift-ring-builder object-2.builder add r1z1-$STORAGE_NODE1:6000/sdb1 1
swift-ring-builder object-2.builder add r1z2-$STORAGE_NODE1:6000/sdc1 1
swift-ring-builder object-2.builder add r1z3-$STORAGE_NODE1:6000/sdd1 1
swift-ring-builder object-2.builder add r1z4-$STORAGE_NODE1:6000/sde1 1
swift-ring-builder object-2.builder add r2z1-$STORAGE_NODE2:6000/sdb1 1
swift-ring-builder object-2.builder add r2z2-$STORAGE_NODE2:6000/sdc1 1
swift-ring-builder object-2.builder add r2z3-$STORAGE_NODE2:6000/sdd1 1
swift-ring-builder object-2.builder add r2z4-$STORAGE_NODE2:6000/sde1 1
swift-ring-builder object-2.builder add r3z1-$STORAGE_NODE3:6000/sdb1 1
swift-ring-builder object-2.builder add r3z2-$STORAGE_NODE3:6000/sdc1 1
swift-ring-builder object-2.builder add r3z3-$STORAGE_NODE3:6000/sdd1 1
swift-ring-builder object-2.builder add r3z4-$STORAGE_NODE3:6000/sde1 1
swift-ring-builder object-2.builder rebalance
swift-ring-builder container.builder create 10 3 1
swift-ring-builder container.builder add r1z1-$STORAGE_NODE1:6001/sdb1 1
swift-ring-builder container.builder add r1z2-$STORAGE_NODE1:6001/sdc1 1
swift-ring-builder container.builder add r1z3-$STORAGE_NODE1:6001/sdd1 1
swift-ring-builder container.builder add r1z4-$STORAGE_NODE1:6001/sde1 1
swift-ring-builder container.builder add r2z1-$STORAGE_NODE2:6001/sdb1 1
swift-ring-builder container.builder add r2z2-$STORAGE_NODE2:6001/sdc1 1
swift-ring-builder container.builder add r2z3-$STORAGE_NODE2:6001/sdd1 1
swift-ring-builder container.builder add r2z4-$STORAGE_NODE2:6001/sde1 1
swift-ring-builder container.builder add r3z1-$STORAGE_NODE3:6001/sdb1 1
swift-ring-builder container.builder add r3z2-$STORAGE_NODE3:6001/sdc1 1
swift-ring-builder container.builder add r3z3-$STORAGE_NODE3:6001/sdd1 1
swift-ring-builder container.builder add r3z4-$STORAGE_NODE3:6001/sde1 1
swift-ring-builder container.builder rebalance
swift-ring-builder account.builder create 10 3 1
swift-ring-builder account.builder add r1z1-$STORAGE_NODE1:6002/sdb1 1
swift-ring-builder account.builder add r1z2-$STORAGE_NODE1:6002/sdc1 1
swift-ring-builder account.builder add r1z3-$STORAGE_NODE1:6002/sdd1 1
swift-ring-builder account.builder add r1z4-$STORAGE_NODE1:6002/sde1 1
swift-ring-builder account.builder add r2z1-$STORAGE_NODE2:6002/sdb1 1
swift-ring-builder account.builder add r2z2-$STORAGE_NODE2:6002/sdc1 1
swift-ring-builder account.builder add r2z3-$STORAGE_NODE2:6002/sdd1 1
swift-ring-builder account.builder add r2z4-$STORAGE_NODE2:6002/sde1 1
swift-ring-builder account.builder add r3z1-$STORAGE_NODE3:6002/sdb1 1
swift-ring-builder account.builder add r3z2-$STORAGE_NODE3:6002/sdc1 1
swift-ring-builder account.builder add r3z3-$STORAGE_NODE3:6002/sdd1 1
swift-ring-builder account.builder add r3z4-$STORAGE_NODE3:6002/sde1 1
swift-ring-builder account.builder rebalance
